authentication/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/', views.register_page, name="register"),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_page, name="logout"),
    path('profile/', views.my_profile_page, name="my_profile"),
    path('profile/<int:user_id>', views.profile_page, name="profile"),
    path('profile/search', views.search_users_page, name="search_users"),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.main_page, name='main'),
    path('my_articles', views.articles_by_user_page, name='articles_by_user'),
    path('my_articles/<int:article_id>', views.edit_article_page, name='edit_article'),
    path('my_articles/delete/<int:article_id>', views.delete_article, name='delete_article'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign/', include('authentication.urls')),
    path('', include('campus_app.urls')),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
import sys
from django.core.validators import MinValueValidator, FileExtensionValidator
from django.core.exceptions import ValidationError


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        # """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if 'createsuperuser' in sys.argv:
            first_name = input('Enter first name: ')
            extra_fields.setdefault('first_name', first_name)

            last_name = input('Enter last name: ')
            extra_fields.setdefault('last_name', last_name)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = models.CharField(
        max_length=40,
        help_text="Required. 40 characters or fewer. Letters, digits and @/./+/-/_ only.",
        error_messages={
            "unique": "A user with that username already exists.",
        },
    )
    email = models.EmailField(unique=True)
    CAMPUS_TYPE_CHOICES = (
        ('teacher', 'Викладач'),
        ('student', 'Студент'),
    )

    def file_size_validator(image: models.ImageField):
        """
        Function that checks whether file size not exceed the limit
        :param image: django.db.models.ImageField, user's image
        :return: None, ValidationError if image size exceeds the limit
        """
        file_size = image.file.size
        megabyte_limit = 2.5
        if file_size > megabyte_limit * 1024 * 1024:
            raise ValidationError(f"File size should be {megabyte_limit} Mb")

    photo = models.ImageField(upload_to='avatars', validators=[
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
        file_size_validator])
    campus_type = models.CharField(max_length=8, choices=CAMPUS_TYPE_CHOICES, default='student')
    bio = models.TextField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    objects = CustomUserManager()
    REQUIRED_FIELDS = []

    def __str__(self):
        """
        Magic method is redefined to show all information about User.
        :return: user id, user first_name, user middle_name, user last_name,
                 user email, user password, user updated_at, user created_at,
                 user role, user is_active
        """
        return f"'id': {self.id}, 'email': '{self.email}'"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of User object.
        :return: class, id
        """
        return f"{User.__name__}(id={self.id})"

    @staticmethod
    def get_by_id(user_id):
        """
        :param user_id: SERIAL: the id of a user to be found in the DB
        :return: user object or None if a user with such ID does not exist
        """
        custom_user = User.objects.filter(id=user_id).first()
        return custom_user if custom_user else None

    @staticmethod
    def get_by_email(email):
        """
        Returns user by email
        :param email: email by which we need to find the user
        :type email: str
        :return: user object or None if a user with such ID does not exist
        """
        custom_user = User.objects.filter(email=email).first()
        return custom_user if custom_user else None

    @staticmethod
    def delete_by_id(user_id):
        """
        :param user_id: an id of a user to be deleted
        :type user_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        user_to_delete = User.objects.filter(id=user_id).first()
        if user_to_delete:
            User.objects.filter(id=user_id).delete()
            return True
        return False

    @staticmethod
    def create(email, password1, password2, username):
        """
        :param username: username of a user
        :type username: str
        :param email: email of a user
        :type email: str
        :param password1: password of a user
        :type password1: str
        :param password2: confirm password of a user
        :type password2: str
        :return: a new user object which is also written into the DB
        """
        if len(username) <= 40 and \
                len(email) <= 100 and \
                password1 == password2 and \
                len(email.split('@')) == 2 and \
                len(User.objects.filter(email=email)) == 0:
            custom_user = User(email=email, username=username, password=password1)
            custom_user.save()
            return custom_user
        return None

    def update(self,
               password=None,
               username=None,
               bio=None):
        """
        Updates user profile in the database with the specified parameters.\n
        :param password: password of a user
        :type password: str
        :param username: username of a user
        :type username: str
        :param bio: username of a user
        :type bio: str
        :return: None
        """
        user_to_update = User.objects.filter(email=self.email).first()

        if password is not None:
            user_to_update.set_password(password)
        if username is not None:
            user_to_update.username = username
        if bio is not None:
            user_to_update.bio = bio
        user_to_update.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all users
        """
        return User.objects.all()

campus_app/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, FileExtensionValidator
from django.db import models
from django.conf import settings


class Article(models.Model):
    ARTICLE_TYPE_CHOICES = (
        ('laba', "Лабораторна робота"),
        ('kursova', "Курсова робота"),
        ('bach_diplom', "Бакалаврська робота"),
        ('mag_diplom', "Магістерська робота"),
    )
    name = models.CharField(max_length=256, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def file_size_validator(file: models.FileField):
        """
        Function that checks whether file size not exceed the limit
        :param image: django.db.models.ImageField, user's image
        :return: None, ValidationError if image size exceeds the limit
        """
        file_size = file.file.size
        megabyte_limit = 10
        if file_size > megabyte_limit * 1024 * 1024:
            raise ValidationError(f"File size should be {megabyte_limit} Mb")

    file = models.FileField(upload_to="articles", validators=[FileExtensionValidator(
        allowed_extensions=['pdf', 'docx', 'doc']),
        file_size_validator])
    description = models.TextField(blank=True)
    type = models.CharField(max_length=64, choices=ARTICLE_TYPE_CHOICES, default='laba')
    created_at = models.DateTimeField(editable=False, auto_now_add=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Article.
        :return: subject id and theme
        """
        return f"{self.name}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Article class.
        :return: class, id
        """
        return f"{Article.__name__}(id={self.id})"

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, forms
from .models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'photo', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username','autofocus': 'autofocus'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'password1': forms.TextInput(attrs={'placeholder': 'Password'}),
            'password2': forms.TextInput(attrs={'placeholder': 'Confirm password'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class UserProfileForm(forms.ModelForm):
    password = forms.CharField(required=False, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['photo', 'bio', 'password']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

authentication/views.py
from django.shortcuts import render, redirect

from .filters import UserFilter
from .forms import UserForm, UserProfileForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import User
from campus_app.models import Article


def register_page(request):
    """ Register function returns register page """
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
        else:
            messages.error(request, f'Виникла помилка під час реєстрації\n{form.errors}')
    return render(request, 'authentication/register.html', {'form': form})


def login_page(request):
    """ Login function returns login page """
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            messages.error(request, 'Виникла помилка під час авторизації')
    return render(request, 'authentication/login.html', {})


@login_required
def my_profile_page(request):
    """ My profile function returns user profile page """
    user = request.user

    form = UserProfileForm(instance=user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user.update(bio=form.cleaned_data["bio"])
            return redirect('my_profile')
        else:
            messages.error(request, f'Виникла помилка {form.errors} під час редагування, спробуйте ще раз')
    return render(request, 'authentication/my_profile.html', {'form': form})


def profile_page(request, user_id):
    """ Subject function returns a template with subjects and tasks from DB based on user """
    user = User.objects.filter(id=user_id).first()
    user_articles = user.article_set.all()
    return render(request, 'authentication/profile.html', {'user': user, 'articles': user_articles})


def search_users_page(request):
    """ Subject function returns a template with subjects and tasks from DB based on user """

    f = UserFilter(queryset=None)
    if request.method == "GET":
        f = UserFilter(request.GET, queryset=User.objects.all())
    return render(request, 'authentication/search_users.html', {'filter': f})


@login_required
def logout_page(request):
    """ Logout function returns logout user """
    logout(request)
    return redirect('main')

templates/authentication/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}

{% block content %}
    <div class="d-flex align-items-center flex-column justify-content-center vh-100" id="header">
        <div class="border" style="padding: 86px 250px 100px">
            <h1 class="display-4 text-center pb-5">Login</h1>
            <form class="" action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input name="email" class="form-control form-control-lg" autofocus="autofocus" placeholder="Ел.пошта" type="email"
                           required>
                </div>
                <div class="form-group">
                    <input name="password" class="form-control form-control-lg" placeholder="Пароль" type="password"
                           required>
                </div>
                <div class="form-group d-flex flex-row-reverse">
                    <button class="btn btn-primary btn-lg" style="padding: 8px 30px">Увійти</button>
                </div>
            </form>
            <p class="mt-3">Не маєте акаунту, створіть новий - <a class="font-weight-bold" href="{% url 'register' %}">Зареєструватись</a></p>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show bg-warning" role="alert">
                    <strong>Помилка: </strong> {{ message|safe }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/authentication/my_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профіль{% endblock title %}

{% block content %}

    {% include 'navbar.html' %}
    <div class="mx-5 w-75">
        <div class="d-flex align-items-center">
            <h2 class="py-3 mr-4">Мій профіль</h2>
            <img src="{{ request.user.photo.url }}" alt="Аватар" style="height: 50px; border-radius: 50%">
        </div>
        <h4 class="">Статус: {{ request.user.get_campus_type_display }}</h4>

        <form class="mt-4 w-75" action="" method="post" enctype="multipart/form-data" style="font-size: 20px">
            {% csrf_token %}
            <div class="form-group">
                <label for="score">Ел. Пошта: </label>
                {{ request.user.email }}
            </div>
            <div class="form-group">
                <label for="deadline">Про себе</label>
                {{ form.bio }}
            </div>
            <div class="form-group d-flex flex-row-reverse">
                <button type="submit" class="btn btn-success rounded py-2 px-2 h-25 my-3 border-0">Зберегти</button>
            </div>
        </form>
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show bg-warning" role="alert">
                <strong>Помилка: </strong> {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/authentication/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профіль{% endblock title %}

{% block content %}

    {% include 'navbar.html' %}
    <div class="mx-5 w-75" style="font-size: 20px">
        <div class="d-flex align-items-center">
            <h2 class="py-3 mr-4">Профіль {{ user.username }}</h2>
            <img src="{{ user.photo.url }}" alt="Аватар" style="height: 50px; border-radius: 50%">
        </div>
        <h4 class="">Статус: {{ user.get_campus_type_display }}</h4>
        <div class="form-group">
            <strong>Ел. Пошта: </strong>
            {{ user.email }}
        </div>
        {% if user.bio %}
            <div class="form-group">
                <strong>Про себе</strong>
                <p>{{ user.bio }}</p>
            </div>
        {% endif %}
        <div class="mt-3">
            {% if articles %}
                <h2 class="mt-3">Роботи автора</h2>
                <table class="table table-responsive-md table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Назва роботи</th>
                        <th scope="col">Тип</th>
                        <th scope="col">Опис</th>
                        <th scope="col">Створено</th>
                        <th scope="col">Посилання</th>
                    </tr>
                    </thead>
                    <tbody id="data_sets_table">
                    {% if articles %}
                        {% for article in articles %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ article.name }}</td>
                                <td>{{ article.get_type_display }}</td>
                                <td>{{ article.description }}</td>
                                <td style="width: 200px">{{ article.created_at }}</td>
                                <td><a target="_blank" href="{{ article.file.url }}">Завантажити</a></td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            {% else %}
                <h2 class="text-center py-4">Тут ще не має жодної роботи!</h2>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/authentication/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}

{% block content %}

    <div class="d-flex align-items-center flex-column justify-content-center vh-100" id="header">
        <div class="border" style="padding: 86px 250px">
            <h1 class="display-4 text-center pb-5">Register</h1>
            <form class="" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Ім'я користувача</label>
                    {{ form.username }}
                </div>
                 <div class="form-group">
                    <label for="avatar">Аватар</label>
                    {{ form.photo }}
                </div>
                <div class="form-group">
                    <label for="email">Ел.пошта</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="username">Пароль</label>
                    {{ form.password1 }}
                </div>
                <div class="form-group">
                    <label for="username">Підтвердження паролю</label>
                    {{ form.password2 }}
                </div>
                <div class="form-group d-flex flex-row-reverse">
                    <button type="submit" class="btn btn-primary btn-lg" style="padding: 8px 30px">Зареєструватись
                    </button>
                </div>
            </form>
            <p class="mt-3">Вже маєте акаунт? <a class="font-weight-bold" href="{% url 'login' %}">Авторизуватись</a>
            </p>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show bg-warning" role="alert">
                    <strong>Помилка: </strong> {{ message|safe }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/authentication/search_users.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профіль{% endblock title %}

{% block content %}

    {% include 'navbar.html' %}
    <div class="mx-5">
        <div class="d-flex align-items-center">
            <h2 class="py-3">Пошук користувачів</h2>
        </div>
        <form method="get" class="d-lg-flex justify-content-lg-between align-items-center w-75">
            {{ filter.form.as_p }}
            <button type="submit" class="btn btn-lg btn-dark h-25">Шукати</button>
        </form>
        {% if filter.qs %}
            <div class="mt-4">
                <table class="table table-responsive-sm table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Аватар</th>
                        <th scope="col">Ім`я користувача</th>
                        <th scope="col">Пошта користувача</th>
                    </tr>
                    </thead>
                    <tbody id="data_sets_table">

                    {% for user in filter.qs %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><img src="{{ user.photo.url }}" alt="Аватар"
                                     style="height: 24px; border-radius: 50%"></td>
                            <td><a href="{% url 'profile' user.id %}">{{ user.username }}</a></td>
                            <td>{{ user.email }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        {% else %}
            <h2 class="text-center py-4">Нікого не знайдено!</h2>
        {% endif %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show bg-warning" role="alert">
                <strong>Помилка: </strong> {{ message|safe }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>

{% endblock %}